@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package net.earthcomputer.bedrockified;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;